Fix nightly Rust build of prost
by going back to upstream prost version

error: failed to load source for dependency `prost`

Caused by:
  Unable to update https://github.com/MaterializeInc/prost#17cc373b

Caused by:
  failed to update submodule `prost-build/third-party/protobuf`

Caused by:
  failed to parse url for submodule `prost-build/third-party/protobuf`: `git@github.com:protocolbuffers/protobuf`

Caused by:
  relative URL without a base