parallel-workload test
Reproduces panics:
bin/parallel-workload-test --threads=100 --runtime=7200 --seed=173227
thread 'coordinator' panicked at 'cannot fail to peek: CollectionMissing(User(23531))', /home/deen/git/materialize3/src/adapter/src/util.rs:280:23
thread 'coordinator' panicked at 'Dataflow oneshot-select-t1257 requested as_of (Antichain { elements: [1688594212000] }) not >= since (Antichain { elements: [1688594213108] })', src/adapter/src/coord/dataflows.rs:260:13